site_name: Paleofuturistic Python Project
site_author: Paleofuturistic Python
site_description: Development flow as Paleofuturistic Python

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en

nav:
  - Home: index.md
